# Generated by Django 2.2 on 2019-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='logo',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
