# Generated by Django 2.2 on 2019-04-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_parametre_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=80)),
                ('specialite', models.CharField(max_length=20)),
                ('image', models.FileField(blank=True, upload_to='post_image')),
            ],
        ),
    ]
