# Generated by Django 2.2 on 2019-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prix',
            name='service1',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prix',
            name='service2',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prix',
            name='service3',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prix',
            name='service4',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
    ]
