# Generated by Django 2.2 on 2019-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190504_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='post_image')),
                ('experience', models.IntegerField()),
                ('nbrclient', models.IntegerField()),
                ('nbrdoctor', models.IntegerField()),
                ('nbrstaff', models.IntegerField()),
            ],
        ),
    ]
