# Generated by Django 2.2 on 2019-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='prenom',
            field=models.CharField(max_length=80),
        ),
    ]
